api_platform:
    title: Option Selection API
    version: 1.0.0
    formats:
        json:
            mime_types:
                - application/json
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
