api_platform:
    title: Option Selection API
    version: 1.0.0
    formats:
        json:
            mime_types:
                - application/json
        jsonld:
            mime_types:
                - application/ld+json
        html:
            mime_types:
                - text/html
    docs_formats:
        html:
            mime_types:
                - text/html
        jsonopenapi:
            mime_types:
                - application/vnd.openapi+json
        jsonld:
            mime_types:
                - application/ld+json
    enable_swagger_ui: true
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
