---
services:
  php:
    volumes:
      - .:/app:cached
      - /app/vendor
      - /app/public/build
    environment:
      SYMFONY_VERSION: ${SYMFONY_VERSION:-}
      STABILITY: ${STABILITY:-stable}
      XDEBUG_MODE: ${XDEBUG_MODE:-develop,debug}
    build:
      context: .
      target: frankenphp_dev

###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5432"
###< doctrine/doctrine-bundle ###
