<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Variant B: Create Parameter, ParameterOption, and ParameterCombination tables
 */
final class Version20260606115645 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create Parameter, ParameterOption, and ParameterCombination tables for Variant B';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE parameter (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_2a9791105e237e06 ON parameter (name)');

        $this->addSql('CREATE TABLE parameter_option (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, parameter_id INT NOT NULL, value VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_bef80a417c56dbd6 ON parameter_option (parameter_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_parameter_value ON parameter_option (parameter_id, value)');
        $this->addSql('ALTER TABLE parameter_option ADD CONSTRAINT fk_bef80a417c56dbd6 FOREIGN KEY (parameter_id) REFERENCES parameter (id) ON DELETE CASCADE NOT DEFERRABLE');

        $this->addSql('CREATE TABLE parameter_combination (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, option1_id INT NOT NULL, option2_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_a09df094bc69547 ON parameter_combination (option1_id)');
        $this->addSql('CREATE INDEX idx_a09df09419733aa9 ON parameter_combination (option2_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_combination ON parameter_combination (option1_id, option2_id)');
        $this->addSql('ALTER TABLE parameter_combination ADD CONSTRAINT fk_a09df094bc69547 FOREIGN KEY (option1_id) REFERENCES parameter_option (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE parameter_combination ADD CONSTRAINT fk_a09df09419733aa9 FOREIGN KEY (option2_id) REFERENCES parameter_option (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE parameter_combination DROP CONSTRAINT fk_a09df09419733aa9');
        $this->addSql('ALTER TABLE parameter_combination DROP CONSTRAINT fk_a09df094bc69547');
        $this->addSql('DROP TABLE parameter_combination');
        $this->addSql('ALTER TABLE parameter_option DROP CONSTRAINT fk_bef80a417c56dbd6');
        $this->addSql('DROP TABLE parameter_option');
        $this->addSql('DROP TABLE parameter');
    }
}
