<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260606080829 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE forbidden_combination (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, option_a_id INT NOT NULL, option_b_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5985478BD3D0F9BB ON forbidden_combination (option_a_id)');
        $this->addSql('CREATE INDEX IDX_5985478BC1655655 ON forbidden_combination (option_b_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_forbidden_pair ON forbidden_combination (option_a_id, option_b_id)');
        $this->addSql('CREATE TABLE parameter (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2A9791105E237E06 ON parameter (name)');
        $this->addSql('CREATE TABLE parameter_option (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, value VARCHAR(255) NOT NULL, position INT NOT NULL, parameter_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BEF80A417C56DBD6 ON parameter_option (parameter_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_parameter_value ON parameter_option (parameter_id, value)');
        $this->addSql('ALTER TABLE forbidden_combination ADD CONSTRAINT FK_5985478BD3D0F9BB FOREIGN KEY (option_a_id) REFERENCES parameter_option (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE forbidden_combination ADD CONSTRAINT FK_5985478BC1655655 FOREIGN KEY (option_b_id) REFERENCES parameter_option (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE parameter_option ADD CONSTRAINT FK_BEF80A417C56DBD6 FOREIGN KEY (parameter_id) REFERENCES parameter (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE forbidden_combination DROP CONSTRAINT FK_5985478BD3D0F9BB');
        $this->addSql('ALTER TABLE forbidden_combination DROP CONSTRAINT FK_5985478BC1655655');
        $this->addSql('ALTER TABLE parameter_option DROP CONSTRAINT FK_BEF80A417C56DBD6');
        $this->addSql('DROP TABLE forbidden_combination');
        $this->addSql('DROP TABLE parameter');
        $this->addSql('DROP TABLE parameter_option');
    }
}
